
version: '3.8'

services:
  web:
    build: .
    ports:
      - "5000:5000"
    volumes:
      - ./templates:/app/templates
    environment:
      FLASK_APP: app
      OPENAI_API_KEY: "your_openai_api_key"
